### ISSUE TITLE
Kinesis load to Athena fails

### ISSUE THREAD

**Issue by cosmorocker** [dlt-hub/dlt#1164]
### dlt version

0.4.6

### Describe the problem

Hi,

I have next error running pipelines in AWS MWAA. The job worked for some time and started failing. The same on local machine works fine. Where should I look to understand the reason?

Error: 
```
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 524, in load
    runner.run_pool(load_step.config, load_step)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/common/runners/pool_runner.py", line 88, in run_pool
    while _run_func():
          ^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/common/runners/pool_runner.py", line 81, in _run_func
    run_metrics = run_f.run(cast(TExecutor, pool))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/load/load.py", line 460, in run
    self.load_single_package(load_id, schema)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/load/load.py", line 402, in load_single_package
    remaining_jobs = self.complete_jobs(load_id, jobs, schema)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/load/load.py", line 279, in complete_jobs
    logger.debug(f"Checking state for job {job.job_id()}")
                                           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'job_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dags/ingest/pull/kinesis_pipeline/kinesis_pipeline.py", line 67, in kinesis_xxx
    logger.info(pipeline.run(dlt_ci_kinesis_stream | _kinesis_xxx_router))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 210, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 255, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 636, in run
    return self.load(destination, dataset_name, credentials=credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 210, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 165, in _wrap
    rv = f(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 151, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 255, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 530, in load
    raise PipelineStepFailed(
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage load when processing package 1711575042.7319355 with exception:

<class 'AttributeError'>
'NoneType' object has no attribute 'job_id'
```

### Steps to reproduce

Code:

```python
@dlt.transformer
def _kinesis_xxx_router(items: list[TDataItem]) -> Iterable[TDataItem]:
    yield from (
        dlt.mark.with_table_name(item, item['event_type'].lower()) for item in items
    )

def kinesis_xxx() -> None:
    pipeline = dlt.pipeline(
        pipeline_name='xxx',
        destination='athena',
        dataset_name='bronze_xxx',
    )

    dlt_ci_kinesis_stream = kinesis_stream(
        KINESIS_XXX_STREAM_NAME,
        parse_json=True,
        initial_at_timestamp=None
    )

    logger.info(pipeline.run(dlt_ci_kinesis_stream | _kinesis_xxx_router))
    logger.info(pipeline.last_trace.last_normalize_info)
```

### Operating system

Linux

### Runtime environment

Airflow

### Python version

3.11

### dlt data source

kinesis

### dlt destination

AWS Athena / Glue Catalog

### Other deployment details

AWS MWAA 2.8.1, Python 3.11

**Comment by cosmorocker** [comment]
looks like it's somehow related to storage. I restarted MWAA and it worked fine. Look like some leftovers of previous runs on file system

**Comment by rudolfix** [comment]
@cosmorocker thx for the report. what has happened is that in the load package there was a job which athena could not handle. and we do not have a proper error information which will give you the exact job name that is causing the problem. this will be fixed in next release.

it makes sense to always wipe out anything from previous run when running on Airflow. our Airflow helper does that, it should work on MWAA as well

did you change the destination type ie. from duckdb to athena?

**Comment by cosmorocker** [comment]
> did you change the destination type ie. from duckdb to athena?

no, nothing was changed when the job started failing. I'll check the helper, because currently I'm not using it

**Comment by rudolfix** [comment]
@sh-rp maybe this is one of the recent problems with Athena? apparently there's a job of a type that Athena does not create instance of
