### ISSUE TITLE
Rest client: Offset paginator fails if total_path is not specified

### ISSUE THREAD

**Issue by sultaniman** [dlt-hub/dlt#1401]
Offset paginator fails with `ValueError` if `total_path` is not given

```py
paginator=OffsetPaginator(
    offset=0,
    limit=10,
    offset_param="offset",
    limit_param="limit",
)
```

**Exception:**

```py
Traceback (most recent call last):
  File "/Users/sultan/Projects/DLT/dlt-openapi/hackathon/marvel/paginate_example.py", line 31, in <module>
    for page in paginate(
  File "/Users/sultan/Projects/DLT/dlt-openapi/.venv/lib/python3.11/site-packages/dlt/sources/helpers/rest_client/client.py", line 221, in paginate
    paginator.update_state(response)
  File "/Users/sultan/Projects/DLT/dlt-openapi/.venv/lib/python3.11/site-packages/dlt/sources/helpers/rest_client/paginators.py", line 139, in update_state
    self._handle_missing_total(response_json)
  File "/Users/sultan/Projects/DLT/dlt-openapi/.venv/lib/python3.11/site-packages/dlt/sources/helpers/rest_client/paginators.py", line 154, in _handle_missing_total
    raise ValueError(
ValueError: Total items is not found in the response in OffsetPaginator. Expected a response with a 'total' key, got
```

@burnash suspects that condition checks are a little flawed
```
it checks for None in one place:
if total_path is None and maximum_value is None:
            raise ValueError("Either `total_path` or `maximum_value` must be provided.")
and for bool in another:
if self.total_path:
```

**Comment by MiguelElGallo** [comment]
Hi, have faced the same, but for now I'm passing always ```total_path=None```.
Maybe pydantic should be used to avoid these things?
