### ISSUE TITLE
`dlt init chess duckdb` does not work with first attempt

### ISSUE THREAD

**Issue by TyDunn** [dlt-hub/dlt#145]
Steps to reproduce:
1. [Installation](https://dlthub.com/docs/installation)
2. [DuckDB destination](https://dlthub.com/docs/destinations#duckdb)

Error:
```
Traceback (most recent call last):
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 260, in extract
    self._extract_source(storage, source, max_parallel_items, workers)
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 755, in _extract_source
    extract_id = self._iterate_source(storage, source, pipeline_schema, max_parallel_items, workers)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 771, in _iterate_source
    extractor = extract(extract_id, source, storage, max_parallel_items=max_parallel_items, workers=workers)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/extract.py", line 82, in extract
    for pipe_item in pipes:
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 422, in __next__
    pipe_item = self._get_source_item()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 580, in _get_source_item
    item = next(gen)
           ^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/chess.py", line 80, in players_games
    r.raise_for_status()
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.chess.com/pub/player/vincentkeymer/games/2022/12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ty/Documents/dlthub/getting-started/chess.py", line 111, in <module>
    info = p.run(
           ^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 101, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 132, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 435, in run
    self.extract(data, table_name=table_name, write_disposition=write_disposition, columns=columns, schema=schema)
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 101, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 75, in _wrap
    rv = f(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 61, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 132, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 269, in extract
    raise PipelineStepFailed(self, "extract", exc, runner.LAST_RUN_METRICS, ExtractInfo()) from exc
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage extract with exception:

<class 'requests.exceptions.HTTPError'>
502 Server Error: Bad Gateway for url: https://api.chess.com/pub/player/vincentkeymer/games/2022/12
```

It also takes a long time for the pipeline to run. There is no output to terminal, so it's not clear that anything is happening for a long time...

**Comment by TyDunn** [comment]
The second time I ran it, I got the same error for a different endpoint:
```
Traceback (most recent call last):
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 260, in extract
    self._extract_source(storage, source, max_parallel_items, workers)
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 755, in _extract_source
    extract_id = self._iterate_source(storage, source, pipeline_schema, max_parallel_items, workers)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 771, in _iterate_source
    extractor = extract(extract_id, source, storage, max_parallel_items=max_parallel_items, workers=workers)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/extract.py", line 82, in extract
    for pipe_item in pipes:
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 422, in __next__
    pipe_item = self._get_source_item()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 580, in _get_source_item
    item = next(gen)
           ^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/chess.py", line 65, in players_games
    for url in archives:
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/common/utils.py", line 129, in flatten_list_or_items
    for items in _iter:
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 627, in __next__
    return super().__next__()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 422, in __next__
    pipe_item = self._get_source_item()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/extract/pipe.py", line 580, in _get_source_item
    item = next(gen)
           ^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/chess.py", line 46, in players_archives
    r.raise_for_status()
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.chess.com/pub/player/rpragchess/games/archives

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ty/Documents/dlthub/getting-started/chess.py", line 111, in <module>
    info = p.run(
           ^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 101, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 132, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 435, in run
    self.extract(data, table_name=table_name, write_disposition=write_disposition, columns=columns, schema=schema)
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 101, in _wrap
    step_info = f(self, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 75, in _wrap
    rv = f(self, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 61, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 132, in _wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ty/Documents/dlthub/getting-started/env/lib/python3.11/site-packages/dlt/pipeline/pipeline.py", line 269, in extract
    raise PipelineStepFailed(self, "extract", exc, runner.LAST_RUN_METRICS, ExtractInfo()) from exc
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage extract with exception:

<class 'requests.exceptions.HTTPError'>
502 Server Error: Bad Gateway for url: https://api.chess.com/pub/player/rpragchess/games/archives
```

**Comment by TyDunn** [comment]
Same thing happened the third time with yet another endpoint. @rudolfix what can I do to avoid this problem? what might we do so that this experience is not what it's like for someone getting started with `dlt`?
