### ISSUE TITLE
Error when using RESTClient.post(): missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by neuromantik33** [dlt-hub/dlt#1542]
### dlt version

0.4.12

### Describe the problem

I'm running a simple pipeline using the `RESTClient` as a source and the `filesystem` as a destination. This is my full stack trace:
```
Traceback (most recent call last):
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/extract/pipe_iterator.py", line 275, in _get_source_item
    pipe_item = next(gen)
  File "/home/drnick/repos/analytics/42next-modeling/nxt/dlt/sources/posthog.py", line 45, in posthog_events
    resp = client.post(
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/sources/helpers/rest_client/client.py", line 143, in post
    return self.request(path, method="POST", json=json, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/sources/helpers/rest_client/client.py", line 132, in request
    prepared_request = self._create_request(
TypeError: RESTClient._create_request() missing 1 required positional argument: 'params'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 431, in extract
    self._extract_source(extract_step, source, max_parallel_items, workers)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 1106, in _extract_source
    load_id = extract.extract(source, max_parallel_items, workers)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/extract/extract.py", line 397, in extract
    self._extract_single_source(
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/extract/extract.py", line 326, in _extract_single_source
    for pipe_item in pipes:
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/extract/pipe_iterator.py", line 159, in __next__
    pipe_item = self._get_source_item()
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/extract/pipe_iterator.py", line 306, in _get_source_item
    raise ResourceExtractionError(pipe.name, gen, str(ex), "generator") from ex
dlt.extract.exceptions.ResourceExtractionError: In processing pipe posthog_events: extraction of resource posthog_events in generator posthog_events caused an exception: RESTClient._create_request() missing 1 required positional argument: 'params'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/drnick/repos/analytics/42next-modeling/nxt/dlt/sources/posthog.py", line 63, in <module>
    load_info = pipeline.run(source)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 222, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 267, in _wrap
    return f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 674, in run
    self.extract(
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 222, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 176, in _wrap
    rv = f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 162, in _wrap
    return f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 267, in _wrap
    return f(self, *args, **kwargs)
  File "/home/drnick/repos/analytics/42next-modeling/.venv/lib/python3.10/site-packages/dlt/pipeline/pipeline.py", line 446, in extract
    raise PipelineStepFailed(
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage extract when processing package 1720098526.1746676 with exception:

<class 'dlt.extract.exceptions.ResourceExtractionError'>
In processing pipe posthog_events: extraction of resource posthog_events in generator posthog_events caused an exception: RESTClient._create_request() missing 1 required positional argument: 'params'
```

### Expected behavior

The expected behaviour is that can I invoke `post()` requests and that it doesn't break.

### Steps to reproduce

```python
@dlt.source
def posthog_source(project_id: int = dlt.config.value, api_key: str = dlt.secrets.value):
    client = RESTClient(
        base_url="https://eu.posthog.com/api",
        headers={"Content-Type": "application/json"},
        auth=BearerTokenAuth(token=api_key),
    )

    @dlt.resource(columns=PosthogEvent, write_disposition="replace")
    def posthog_events(start: datetime, until: datetime):
        resp = client.post(
            path=f"/projects/{project_id}/query",
            json={
                "query": {
                    "kind": "HogQLQuery",
                    "query": events_query.format(start, until),
                }
            },
        )
        yield extract_events(resp.json())

    return posthog_events
```

### Operating system

Linux

### Runtime environment

Local

### Python version

3.10

### dlt data source

https://dlthub.com/docs/general-usage/http/rest-client

### dlt destination

Filesystem & buckets

### Additional information

The problem is quite simple and an easy fix:
```python
def _create_request(
    self,
    path: str,
    method: HTTPMethod,
    params: Dict[str, Any],
    json: Optional[Dict[str, Any]] = None,
    auth: Optional[AuthBase] = None,
    hooks: Optional[Hooks] = None,
) -> Request:
    ...
```
And the invoking code
```python
def post(self, path: str, json: Optional[Dict[str, Any]] = None, **kwargs: Any) -> Response:
    return self.request(path, method="POST", json=json, **kwargs)
```
The workaround atm is to simply add a `params=None` to `post()`.

**Comment by willi-mueller** [comment]
Hi @neuromantik33 , thank you for the report! I can reproduce the error. But I also see that if you use a paginator then the error does not seem to occur. 

Is there a reason you need to call `client.post()` over `client.paginate()`? I looked into the Posthog docs and [they seem to paginate the results](https://posthog.com/docs/api#pagination) with a method that the `client.paginate()` can most likely detect automatically. Would you like to give it a try?

```py
client.paginate(
            path=f"/projects/{project_id}/query",
            method="POST",
            json={
                "query": {
                    "kind": "HogQLQuery",
                    "query": events_query.format(start, until),
                }
            },
        )
```

**Comment by neuromantik33** [comment]
Hi. Thank you for your suggestions. I probably would have used pagination but from what I tested using curl and so forth, I never saw a `next` field to paginate against. This query is maybe a bit experimental since it takes no parameters except a POST body with a _HogQLQuery_ and the response sort of looks like this:
```json
{
  "cache_key": "cache_51387a94332c8aab59b4dcd3bcbf5c30",
  "clickhouse": "SELECT\n    events.uuid AS uuid,\n    events.event AS event,\n    events.properties AS properties,\n    toTimeZone(events.timestamp, %(hogql_val_0)s) AS timestamp,\n    events.distinct_id AS distinct_id,\n    toTimeZone(events.created_at, %(hogql_val_1)s) AS created_at,\n    events.`$session_id` AS `$session_id`,\n    events.`$window_id` AS `$window_id`\nFROM\n    events\nWHERE\n    and(equals(events.team_id, 17683), greaterOrEquals(toTimeZone(events.timestamp, %(hogql_val_2)s), %(hogql_val_3)s), less(toTimeZone(events.timestamp, %(hogql_val_4)s), %(hogql_val_5)s))\nLIMIT 10000 SETTINGS readonly=2, max_execution_time=60, allow_experimental_object_type=1, format_csv_allow_double_quotes=0, max_ast_elements=2000000, max_expanded_ast_elements=2000000, max_query_size=1048576, max_bytes_before_external_group_by=0",
  "columns": [
    "uuid",
    "event",
    "properties",
    "timestamp",
    "distinct_id",
    "created_at",
    "$session_id",
    "$window_id"
  ],
  "error": null,
  "explain": null,
  "hasMore": null,
  "hogql": "SELECT\n    uuid,\n    event,\n    properties,\n    timestamp,\n    distinct_id,\n    created_at,\n    $session_id,\n    $window_id\nFROM\n    events\nWHERE\n    and(greaterOrEquals(timestamp, '2024-05-14T00:00:00'), less(timestamp, '2024-05-15T00:00:00'))\nLIMIT 10000",
  "is_cached": true,
  "last_refresh": "2024-07-03T08:28:15.832191Z",
  "limit": null,
  "metadata": null,
  "modifiers": {
    "bounceRatePageViewMode": "count_pageviews",
    "dataWarehouseEventsModifiers": null,
    "debug": null,
    "inCohortVia": "subquery",
    "materializationMode": "legacy_null_as_null",
    "optimizeJoinedFilters": false,
    "personsArgMaxVersion": "auto",
    "personsJoinMode": null,
    "personsOnEventsMode": "person_id_override_properties_joined",
    "s3TableUseInvalidColumns": null,
    "sessionTableVersion": "auto"
  },
  "next_allowed_client_refresh": "2024-07-03T08:29:15.832195Z",
  "offset": null,
  "query": null,
  "query_status": null,
  "results": [
    [
      "018f7648-eae7-7fc3-8cdb-907c73b1f424",
      "$autocapture",
      "{\"$device_type\":\"Desktop\",\"$raw_user_agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\",\"$feature_flag_payloads\":{},\"$screen_width\":1920,\"$autocapture_disabled_server_side\":false,\"$referrer\":\"$direct\",\"$session_id\":\"018f763e-498c-7c9d-bc34-924fcc3d6208\",\"$lib_version\":\"1.114.1\",\"$active_feature_flags\":[],\"$device_id\":\"018e5ce7-a91e-70af-b602-3d17500d409d\",\"distinct_id\":\"018e5ce7-a91e-70af-b602-3d17500d409d\",\"$viewport_width\":1920,\"$screen_height\":1080,\"$session_recording_network_payload_capture\":{\"capturePerformance\":false},\"$os_version\":\"10.15.7\",\"$browser_version\":124,\"$current_url\":\"https://42next.staging.42.fr/fr/admin/paperwork/tracks/create\",\"$window_id\":\"018f763e-498c-7c9d-bc34-9250940cce5f\",\"$pathname\":\"/fr/admin/paperwork/tracks/create\",\"$viewport_height\":907,\"$insert_id\":\"27eeei86xewajli5\",\"$time\":1715676441.319,\"$session_recording_canvas_recording\":{},\"$referring_domain\":\"$direct\",\"$browser_language\":\"fr-FR\",\"$browser\":\"Chrome\",\"$lib\":\"web\",\"$ce_version\":1,\"$el_text\":\"Question déroulante\",\"$os\":\"Mac OS X\",\"token\":\"phc_8r6byAXtLC8tzrBgEMRrAIPE0yNWOJlqsuiboKvTGOV\",\"$host\":\"42next.staging.42.fr\",\"$event_type\":\"click\",\"$set\":{\"$device_type\":\"Desktop\",\"$referrer\":\"$direct\",\"$os_version\":\"10.15.7\",\"$browser_version\":124,\"$current_url\":\"https://42next.staging.42.fr/fr/admin/paperwork/tracks/create\",\"$pathname\":\"/fr/admin/paperwork/tracks/create\",\"$referring_domain\":\"$direct\",\"$browser\":\"Chrome\",\"$os\":\"Mac OS X\"},\"$set_once\":{\"$initial_device_type\":\"Desktop\",\"$initial_referrer\":\"$direct\",\"$initial_os_version\":\"10.15.7\",\"$initial_browser_version\":124,\"$initial_current_url\":\"https://42next.staging.42.fr/fr/admin/paperwork/tracks/create\",\"$initial_pathname\":\"/fr/admin/paperwork/tracks/create\",\"$initial_referring_domain\":\"$direct\",\"$initial_browser\":\"Chrome\",\"$initial_os\":\"Mac OS X\"},\"$sent_at\":\"2024-05-14T08:47:24.321Z\",\"$plugins_succeeded\":[\"GeoIP (10036)\"],\"$plugins_failed\":[]}",
      "2024-05-14T08:47:21.443000Z",
      "018e5ce7-a91e-70af-b602-3d17500d409d",
      "2024-05-14T08:47:24.741000Z",
      "018f763e-498c-7c9d-bc34-924fcc3d6208",
      "018f763e-498c-7c9d-bc34-9250940cce5f"
    ]
    ...
  ],
  "timezone": "UTC",
  "timings": [
    {
      "k": "./parse_select/parse_select_cpp",
      "t": 0.005850001999988308
    },
    {
      "k": "./parse_select",
      "t": 0.005971468999973695
    },
    {
      "k": "./query",
      "t": 9.335700008250569e-05
    },
    {
      "k": "./replace_placeholders",
      "t": 0.00021367599993027397
    },
    {
      "k": "./max_limit",
      "t": 3.550300004917517e-05
    },
    {
      "k": "./hogql/prepare_ast/clone",
      "t": 0.00023600099996201607
    },
    {
      "k": "./hogql/prepare_ast/create_hogql_database",
      "t": 0.08292953500006206
    },
    {
      "k": "./hogql/prepare_ast/resolve_types",
      "t": 0.0006859399999257221
    },
    {
      "k": "./hogql/prepare_ast",
      "t": 0.08397759600006793
    },
    {
      "k": "./hogql/print_ast/printer",
      "t": 0.00028997300000810355
    },
    {
      "k": "./hogql/print_ast",
      "t": 0.00035042000001794804
    },
    {
      "k": "./hogql",
      "t": 0.08437197000000651
    },
    {
      "k": "./print_ast/create_hogql_database",
      "t": 0.07961302299997897
    },
    {
      "k": "./print_ast/resolve_types",
      "t": 0.0005945520000523175
    },
    {
      "k": "./print_ast/resolve_property_types",
      "t": 0.000573218999988967
    },
    {
      "k": "./print_ast/resolve_lazy_tables",
      "t": 0.0004393140000047424
    },
    {
      "k": "./print_ast/swap_properties",
      "t": 0.00024519900000541384
    },
    {
      "k": "./print_ast/printer",
      "t": 0.0008550459999696614
    },
    {
      "k": "./print_ast",
      "t": 0.0825113409999858
    },
    {
      "k": "./clickhouse_execute",
      "t": 0.07711692300006234
    },
    {
      "k": ".",
      "t": 0.26930238300008114
    }
  ],
  "types": [
    [
      "uuid",
      "UUID"
    ],
    [
      "event",
      "String"
    ],
    [
      "properties",
      "String"
    ],
    [
      "timestamp",
      "DateTime64(6, 'UTC')"
    ],
    [
      "distinct_id",
      "String"
    ],
    [
      "created_at",
      "DateTime64(6, 'UTC')"
    ],
    [
      "$session_id",
      "String"
    ],
    [
      "$window_id",
      "String"
    ]
  ]
}
```
Maybe if I specified a `limit` and an `offset` in my POST query the fields `hasMore` and `offset` might be present and I could infer a page but it seemed unlikely. As you can see, this is not your typical REST endpoint :sweat_smile:

**Comment by willi-mueller** [comment]
I see your point. I'd consider using `paginate()` so that you are safe in case the response is suddenly large enough to be paginated.
