### ISSUE TITLE
`sql_database` source does not load columns with names starting with underscore `_` 

### ISSUE THREAD

**Issue by khoadaniel** [dlt-hub/dlt#1564]
### dlt version

0.5.1

### Describe the problem

I noticed that dlt (0.5.1) does not load postgres columns that start with underscore `_` .
Is it an expected behavior?

Error message:
```
<class 'dlt.extract.exceptions.ResourceExtractionError'>
In processing pipe identifiers: extraction of resource identifiers in generator table_rows caused an exception: "Cursor column '_created_at' does not exist in table 'identifiers'"
```

This column exists in the source table I'm testing:
<img width="763" alt="image" src="https://github.com/dlt-hub/dlt/assets/84840546/1fdf5bbf-c8da-487a-b72f-786f30adb37a">

### Expected behavior

Columns with names starting with underscore `_` should be loaded too.

### `sql_database_pipeline.py`

```
import datetime
import dlt
from sql_database import sql_database


def load_selected_tables_from_database() -> None:

    pipeline = dlt.pipeline(
        pipeline_name="dlt_stryker",
        destination='postgres',
        dataset_name="dlt_stryker",  # destination schema
    )

    source_sql = sql_database(
        schema="public"  # source schema
    ).with_resources("event_sendings", "events", "identifiers")

    source_sql.event_sendings.apply_hints(
        incremental=dlt.sources.incremental(
            cursor_path="_created_at",
            initial_value=datetime.datetime(
                2024, 7, 7, 0, 0, 0, 0, tzinfo=datetime.timezone.utc)
        ),
        primary_key="id",
    )

    source_sql.events.apply_hints(
        incremental=dlt.sources.incremental(
            cursor_path="_created_at",
            initial_value=datetime.datetime(
                2024, 7, 7, 0, 0, 0, 0, tzinfo=datetime.timezone.utc)
        ),
        primary_key="id",
    )

    source_sql.identifiers.apply_hints(
        incremental=dlt.sources.incremental(
            cursor_path="_created_at",
            initial_value=datetime.datetime(
                2024, 7, 7, 0, 0, 0, 0, tzinfo=datetime.timezone.utc)
        ),
        primary_key="id",
    )

    info = pipeline.run(source_sql,
                        write_disposition="append",
                        # refresh="drop_resources",
                        )

    print("==================================")
    print(info)
    print("==================================")
    print(info.load_packages[0])


if __name__ == "__main__":
    load_selected_tables_from_database()

```

### Operating system

Linux

### Runtime environment

Virtual Machine

### Python version

3.10

### dlt data source

Verified source `sql_database` (postgres)

### dlt destination

Postgres

### Additional information

```
(.venv) [ec2-user@ip-10-0-1-1 postgres_stryker_data]$ python3 sql_database_pipeline.py 
2024-07-08 17:54:57,672|[WARNING]|2504249|140458818254656|dlt|schema_types.py|sqla_col_to_column_schema:79|A column with name events contains unknown data type ARRAY which cannot be mapped to `dlt` data type. When using sqlalchemy backend such data will be passed to the normalizer. In case of `pyarrow` backend such data will be ignored. In case of other backends, the behavior is backend-specific.
2024-07-08 17:54:57,677|[WARNING]|2504249|140458818254656|dlt|schema_types.py|sqla_col_to_column_schema:79|A column with name errors contains unknown data type ARRAY which cannot be mapped to `dlt` data type. When using sqlalchemy backend such data will be passed to the normalizer. In case of `pyarrow` backend such data will be ignored. In case of other backends, the behavior is backend-specific.
2024-07-08 17:54:57,677|[WARNING]|2504249|140458818254656|dlt|schema_types.py|sqla_col_to_column_schema:79|A column with name attempted_by contains unknown data type ARRAY which cannot be mapped to `dlt` data type. When using sqlalchemy backend such data will be passed to the normalizer. In case of `pyarrow` backend such data will be ignored. In case of other backends, the behavior is backend-specific.
2024-07-08 17:54:57,678|[WARNING]|2504249|140458818254656|dlt|schema_types.py|sqla_col_to_column_schema:79|A column with name tags contains unknown data type ARRAY which cannot be mapped to `dlt` data type. When using sqlalchemy backend such data will be passed to the normalizer. In case of `pyarrow` backend such data will be ignored. In case of other backends, the behavior is backend-specific.
2024-07-08 17:54:57,839|[INFO]|2504249|140458818254656|dlt|__init__.py|bind:424|Bind incremental on event_sendings with initial_value: 2024-07-07 00:00:00+00:00, start_value: 2024-07-07 00:00:00+00:00, end_value: None
2024-07-08 17:54:57,862|[INFO]|2504249|140458818254656|dlt|__init__.py|bind:424|Bind incremental on identifiers with initial_value: 2024-07-07 00:00:00+00:00, start_value: 2024-07-07 00:00:00+00:00, end_value: None
2024-07-08 17:54:57,885|[INFO]|2504249|140458818254656|dlt|__init__.py|bind:424|Bind incremental on events with initial_value: 2024-07-07 00:00:00+00:00, start_value: 2024-07-07 00:00:00+00:00, end_value: None
Traceback (most recent call last):
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/sql_database/helpers.py", line 57, in __init__
    self.cursor_column = table.c[incremental.cursor_path]
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/sqlalchemy/sql/base.py", line 1608, in __getitem__
    return self._index[key][1]
KeyError: '_created_at'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/extract/pipe_iterator.py", line 274, in _get_source_item
    pipe_item = next(gen)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/sql_database/helpers.py", line 213, in table_rows
    loader = TableLoader(
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/sql_database/helpers.py", line 59, in __init__
    raise KeyError(
KeyError: "Cursor column '_created_at' does not exist in table 'events'"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 433, in extract
    self._extract_source(
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 1149, in _extract_source
    load_id = extract.extract(
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/extract/extract.py", line 404, in extract
    self._extract_single_source(
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/extract/extract.py", line 327, in _extract_single_source
    for pipe_item in pipes:
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/extract/pipe_iterator.py", line 158, in __next__
    pipe_item = self._get_source_item()
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/extract/pipe_iterator.py", line 305, in _get_source_item
    raise ResourceExtractionError(pipe.name, gen, str(ex), "generator") from ex
dlt.extract.exceptions.ResourceExtractionError: In processing pipe events: extraction of resource events in generator table_rows caused an exception: "Cursor column '_created_at' does not exist in table 'events'"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/sql_database_pipeline.py", line 57, in <module>
    load_selected_tables_from_database()
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/sql_database_pipeline.py", line 45, in load_selected_tables_from_database
    info = pipeline.run(source_sql,
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 222, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 267, in _wrap
    return f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 684, in run
    self.extract(
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 222, in _wrap
    step_info = f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 176, in _wrap
    rv = f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 162, in _wrap
    return f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 267, in _wrap
    return f(self, *args, **kwargs)
  File "/home/ec2-user/data_platform_dlt_faircare/apps/dlt/postgres_stryker_data/.venv/lib64/python3.9/site-packages/dlt/pipeline/pipeline.py", line 453, in extract
    raise PipelineStepFailed(
dlt.pipeline.exceptions.PipelineStepFailed: Pipeline execution failed at stage extract when processing package 1720461297.8247967 with exception:

<class 'dlt.extract.exceptions.ResourceExtractionError'>
In processing pipe events: extraction of resource events in generator table_rows caused an exception: "Cursor column '_created_at' does not exist in table 'events'"

```

**Comment by rudolfix** [comment]
@khoadaniel is this problem still there?

**Comment by rudolfix** [comment]
@khoadaniel if the problem persist please ping me on slack, we'll close the issue for now
